# -*- coding: utf-8 -*-
"""assignment1_Q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S_yugu74Z6tjSU2XOC5vlrsi0ADBvPVY

Write a Python program to get the Fibonacci series between 0 to 50
"""

nth= 50
a=0
b=1
print(a)
print(b)
for i in range(1,(nth-1)):
  c=a+b
  print(c)
  a=b
  b=c