# -*- coding: utf-8 -*-
"""assignment1_Q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17DdRk4DrScAuL5a5x5_TfXihsaZeEMvw

#Write a Python program to get the Fibonacci series between 0 to 50
"""

nterms = 50
n1, n2 = 0, 1
count = 0
if nterms<=0:
  print("enter the positive number")
elif nterms==1:
  print("fibonacci sequence till", nterms, ":")
  print(n1)
else:
  print("fibonacci sequence")
  while count<nterms:
    print(n1)
    nth= n1+n2
    n1=n2
    n2=nth
    count+=1