# -*- coding: utf-8 -*-
"""assignment1_Q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aoGnOu_qc_0r50NsZC_UKyzBpiZuxCmE

#Write a Python program to get the Fibonacci series between 0 to 50
"""

nterms = 50
n1, n2 = 0, 1
count = 0
if nterms>=0:
  print("fibonacci sequence")
  while count<nterms:
    print(n1)
    sum=n1+n2
    n1=n2
    n2=sum
    count+=1