# -*- coding: utf-8 -*-
"""Assignment1_Q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FHrNr6bdT23Yc-ID-zLYLAsJtD2QvW0p

Write a Python program that accepts a word from the user and reverse it.
"""

a= str(input("enter your word--->"))[::-1]
print(a)